# -*- coding: utf-8 -*-
"""Main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeaEGSnAL6EMxYD8UCsoXIMR2SVnxnxA
"""

!pip install kivy

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from kivy.app import App
# from kivy.uix.boxlayout import BoxLayout
# from kivy.uix.label import Label
# from kivy.uix.textinput import TextInput
# from kivy.uix.button import Button
# from kivy.uix.scrollview import ScrollView
# import math
# 
# class CarpetaCalculator(BoxLayout):
#     def __init__(self, **kwargs):
#         super(CarpetaCalculator, self).__init__(**kwargs)
#         self.orientation = 'vertical'
#         self.padding = 10
#         self.spacing = 10
# 
#         # Títulos
#         self.add_widget(Label(text="Calculadora de Carpeta Antiderrame", font_size=20, bold=True))
# 
#         # Inputs
#         self.add_widget(Label(text="Ancho (m):"))
#         self.ancho_input = TextInput(text="2.0", multiline=False)
#         self.add_widget(self.ancho_input)
# 
#         self.add_widget(Label(text="Largo (m):"))
#         self.largo_input = TextInput(text="2.0", multiline=False)
#         self.add_widget(self.largo_input)
# 
#         self.add_widget(Label(text="Altura (m):"))
#         self.altura_input = TextInput(text="0.10", multiline=False)
#         self.add_widget(self.altura_input)
# 
#         # Botón
#         self.calcular_button = Button(text="Calcular y Mostrar", size_hint=(1, 0.5))
#         self.calcular_button.bind(on_press=self.calcular)
#         self.add_widget(self.calcular_button)
# 
#         # Área de resultados
#         self.scroll = ScrollView(size_hint=(1, None), size=(400, 200))
#         self.result_label = Label(text="", size_hint_y=None, height=200)
#         self.scroll.add_widget(self.result_label)
#         self.add_widget(self.scroll)
# 
#     def calcular_carpeta_antiderrame_exacto(self, ancho_base, largo_base, altura_borde):
#         try:
#             PRECIO_TELA_PVC = 7790
#             PRECIO_ESPUMA_LAMINA = 55000
#             MANO_OBRA_FIJA = 15000
#             MARGEN_GANANCIA = 1.0
# 
#             ANCHO_ROLLO = 1.52
#             ADICIONAL_PERIMETRO = 0.10
#             ADICIONAL_BORDES = 0.20
#             ANCHO_BORDE = 0.10
#             COSTURA_PLIEGUE = 0.04
#             TIRA_ESPUMA_LENGTH = 1.7
#             CORTES_POR_LAMINA = 15
# 
#             consumo_tela_por_borde = {0.10: 0.34, 0.15: 0.44, 0.20: 0.54, 0.25: 0.64, 0.30: 0.74}
# 
#             if altura_borde not in consumo_tela_por_borde:
#                 return "Error: Altura de borde no valida. Use: 0.10, 0.15, 0.20, 0.25, 0.30"
# 
#             consumo_por_borde = consumo_tela_por_borde[altura_borde]
# 
#             ancho_base_real = ancho_base + ADICIONAL_PERIMETRO
#             largo_base_real = largo_base + ADICIONAL_PERIMETRO
# 
#             short = min(ancho_base_real, largo_base_real)
#             long = max(ancho_base_real, largo_base_real)
# 
#             cortes_ancho = math.ceil(short / ANCHO_ROLLO)
#             metros_tela_base = long * cortes_ancho
# 
#             used_in_last = short - (cortes_ancho - 1) * ANCHO_ROLLO
#             remaining_width = ANCHO_ROLLO - used_in_last if cortes_ancho > 1 else ANCHO_ROLLO
# 
#             number_fit = int(remaining_width / consumo_por_borde)
# 
#             metros_tela_bordes = 0
#             if number_fit < 4:
#                 remaining_to_cut = 4 - number_fit
#                 bordes_por_ancho = int(ANCHO_ROLLO / consumo_por_borde)
#                 filas = math.ceil(remaining_to_cut / bordes_por_ancho)
#                 max_borde_length = max(ancho_base + ADICIONAL_BORDES, largo_base + ADICIONAL_BORDES)
#                 metros_tela_bordes = filas * max_borde_length
# 
#             metros_tela_total = metros_tela_base + metros_tela_bordes
#             if number_fit >= 4:
#                 metros_tela_total += 0.1
# 
#             costo_tela = metros_tela_total * PRECIO_TELA_PVC
# 
#             perimetro = 2 * (ancho_base + largo_base)
#             tiras_necesarias = int(perimetro / TIRA_ESPUMA_LENGTH + 0.99)
#             precio_por_tira = PRECIO_ESPUMA_LAMINA / CORTES_POR_LAMINA
#             costo_espuma = tiras_necesarias * precio_por_tira
# 
#             costo_materiales = costo_tela + costo_espuma
#             costo_produccion = costo_materiales + MANO_OBRA_FIJA
#             precio_venta = costo_produccion * (1 + MARGEN_GANANCIA)
#             ganancia_neta = precio_venta - costo_produccion
# 
#             return {
#                 'dimensiones': {'base_original': (ancho_base, largo_base), 'base_real': (ancho_base_real, largo_base_real),
#                                 'area_base': ancho_base * largo_base, 'perimetro': perimetro, 'altura_borde': altura_borde,
#                                 'ancho_borde': ANCHO_BORDE},
#                 'tela': {'base': {'metros': metros_tela_base, 'cortes_ancho': cortes_ancho, 'adicional_perimetro': ADICIONAL_PERIMETRO},
#                          'bordes': {'consumo_por_borde': consumo_por_borde, 'metros_total': metros_tela_bordes,
#                                     'adicional_bordes': ADICIONAL_BORDES, 'number_fit': number_fit},
#                          'total_metros': metros_tela_total, 'costo_total': costo_tela},
#                 'espuma': {'tiras_necesarias': tiras_necesarias, 'precio_por_tira': precio_por_tira, 'costo_total': costo_espuma},
#                 'costos': {'materiales': costo_materiales, 'mano_obra': MANO_OBRA_FIJA, 'produccion': costo_produccion,
#                            'venta': precio_venta, 'ganancia': ganancia_neta, 'margen': MARGEN_GANANCIA * 100},
#                 'especificaciones': {'capacidad_litros': ancho_base * largo_base * altura_borde * 1000,
#                                     'proceso': 'Soldado alta frecuencia', 'costura_pliegue': COSTURA_PLIEGUE}
#             }
#         except Exception as e:
#             return f"Error en calculo: {str(e)}"
# 
#     def calcular(self, instance):
#         try:
#             ancho = float(self.ancho_input.text)
#             largo = float(self.largo_input.text)
#             altura = float(self.altura_input.text)
# 
#             if ancho <= 0 or largo <= 0 or altura <= 0:
#                 self.result_label.text = "Error: Las dimensiones deben ser mayores a 0."
#                 return
# 
#             resultados = self.calcular_carpeta_antiderrame_exacto(ancho, largo, altura)
#             if isinstance(resultados, dict):
#                 output = "============================================================\n"
#                 output += "PRESUPUESTO EXACTO - CARPETA ANTIDERRAME\n"
#                 output += "============================================================\n\n"
#                 output += "DIMENSIONES:\n"
#                 output += f"   - Base original: {resultados['dimensiones']['base_original'][0]}m x {resultados['dimensiones']['base_original'][1]}m\n"
#                 output += f"   - Base real: {resultados['dimensiones']['base_real'][0]}m x {resultados['dimensiones']['base_real'][1]}m\n"
#                 output += f"   - Area util: {resultados['dimensiones']['area_base']:.2f} m²\n"
#                 output += f"   - Perimetro: {resultados['dimensiones']['perimetro']:.2f} m\n"
#                 output += f"   - Bordes: {(resultados['dimensiones']['altura_borde']*100):.0f}cm x {(resultados['dimensiones']['ancho_borde']*100):.0f}cm\n"
#                 output += f"   - Capacidad: {resultados['especificaciones']['capacidad_litros']:,.0f} litros\n\n"
#                 output += "TELA PVC (1.52m ancho):\n   BASE:\n"
#                 output += f"     - Metros: {resultados['tela']['base']['metros']:.2f}m\n"
#                 output += f"     - Cortes ancho: {resultados['tela']['base']['cortes_ancho']}\n"
#                 output += f"     - Adicional perimetro: +{resultados['tela']['base']['adicional_perimetro']}m\n"
#                 output += "   BORDES:\n"
#                 output += f"     - Consumo por borde: {resultados['tela']['bordes']['consumo_por_borde']}m\n"
#                 output += f"     - Adicional por borde: +{resultados['tela']['bordes']['adicional_bordes']}m\n"
#                 output += f"     - Number fit in remaining: {resultados['tela']['bordes']['number_fit']}\n"
#                 output += f"     - Metros bordes: {resultados['tela']['bordes']['metros_total']:.2f}m\n"
#                 output += f"     - Total metros tela: {resultados['tela']['total_metros']:.2f}m\n"
#                 output += f"     - Costo tela: ${resultados['tela']['costo_total']:,.0f}\n\n"
#                 output += "ESPUMA:\n"
#                 output += f"     - Tiras necesarias: {resultados['espuma']['tiras_necesarias']}\n"
#                 output += f"     - Precio por tira: ${resultados['espuma']['precio_por_tira']:,.0f}\n"
#                 output += f"     - Costo total: ${resultados['espuma']['costo_total']:,.0f}\n\n"
#                 output += "COSTOS:\n"
#                 output += f"   - Materiales: ${resultados['costos']['materiales']:,.0f}\n"
#                 output += f"   - Mano obra: ${resultados['costos']['mano_obra']:,.0f}\n"
#                 output += f"   - COSTO PRODUCCION: ${resultados['costos']['produccion']:,.0f}\n\n"
#                 output += "PRECIO DE VENTA (MARGEN 100%):\n"
#                 output += f"   - Precio unidad: ${resultados['costos']['venta']:,.0f}\n"
#                 output += f"   - Ganancia: ${resultados['costos']['ganancia']:,.0f}\n\n"
#                 output += "PROCESO:\n"
#                 output += f"   - Proceso: {resultados['especificaciones']['proceso']}\n"
#                 output += f"   - Costura pliegue: +{resultados['especificaciones']['costura_pliegue']}m\n"
#                 output += "============================================================\n"
#                 self.result_label.text = output
#             else:
#                 self.result_label.text = resultados
#         except ValueError:
#             self.result_label.text = "Error: Ingresa valores numéricos válidos."
# 
# class CarpetaApp(App):
#     def build(self):
#         return CarpetaCalculator()
# 
# if __name__ == '__main__':
#     CarpetaApp().run()

!python main.py
# Trigger build
